sudo: required

services:
  - docker

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  - NAME=nodecraft IMAGE=zihao/$NAME:latest CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - echo $GCLOUD_KEY_BASE64 | base64 --decode > gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.json
  - gcloud config set project gcloud-zihao
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials zz-gke
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $IMAGE .;
    docker run -d $IMAGE;
    docker ps -a;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE;
    kubectl apply -f kube;
    kubectl patch deployment $NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`env TZ="UTC" date +'%F_%s'`\"}}}}}";
    fi
