sudo: required

language: node_js
node_js:
  - node

services:
  - docker

install:
  - yarn 

script:
  - node index.js &
  - sleep 3
  - curl localhost:8000/healthz

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t zihao/nodecraft .;
    docker run -d zihao/nodecraft;
    docker ps -a;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push zihao/nodecraft;
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl;
    chmod +x kubectl;
    echo "$KUBE_CONFIG_BASE64" | base64 --decode > config;
    ./kubectl --kubeconfig config apply -f kube;
    ./kubectl --kubeconfig config set --namespace=production image deployment/nodecraft nodecraft=zihao/nodecraft;
    rm config;
    fi
