apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodecraft
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - nodecraft.cloud.zihao.me
    secretName: nodecraft-tls
  rules:
  - host: nodecraft.cloud.zihao.me
    http:
      paths:
      - backend:
          serviceName: nodecraft
          servicePort: 80
        path: /
