apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector: {{ include "selector" . | nindent 4 }}
