name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Login
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        env:
          IMAGE: zihao/nodecraft
        run: |
          docker pull $IMAGE:latest || true
          docker build -t $IMAGE:$GITHUB_SHA -t $IMAGE:latest --cache-from $IMAGE:latest .
          docker push $IMAGE:$GITHUB_SHA
          docker push $IMAGE:latest
      - name: GKE Deploy
        run: |
          echo {{ secrets.GCLOUD_PRIVATE_KEY }} | base64 --decode > gcloud.json
          gcloud auth activate-service-account --key-file gcloud.json
          gcloud config set project gcloud-zihao
          gcloud config set compute/zone us-west1-a
          gcloud components update kubectl
          gcloud container clusters get-credentials zz-gke
          curl -L https://git.io/get_helm.sh | bash
          helm plugin install https://github.com/rimusz/helm-tiller
          helm tiller run helm upgrade nodecraft ./helm
      - name: Discord Succeeded
        uses: docker://appleboy/drone-discord:1.2.3-linux-amd64
        env:
          PLUGIN_GITHUB: "true"
          WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          COLOR: "#49C39E"
          DISCORD_MESSAGE: "[[${{ github.workflow }}]] [${{ github.repository }}:${{ github.ref }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks) Succeeded"
      - name: Discord Failed
        if: failure()
        uses: docker://appleboy/drone-discord:1.2.3-linux-amd64
        env:
          PLUGIN_GITHUB: "true"
          WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          COLOR: "#D40E0D"
          DISCORD_MESSAGE: "[[${{ github.workflow }}]] [${{ github.repository }}:${{ github.ref }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks) Failed"
# env:
#   - NAME=nodecraft IMAGE=zihao/$NAME:latest CLOUDSDK_CORE_DISABLE_PROMPTS=1
